syntax = "proto3";

option csharp_namespace = "ApiGateway";

service UserGrpc {
	rpc RegisterUser (RegisterUserGrpcRequest) returns (RegisterUserGrpcResponse);
	rpc UpdateUser (UpdateUserGrpcRequest) returns (UpdateUserGrpcResponse);
	rpc AuthenticationUser (AuthenticationUserGrpcRequest) returns (AuthenticationUserGrpcResponse);
	rpc GetUser (GetUserGrpcRequest) returns (GetUserGrpcResponse); 
	rpc DeleteUser (DeleteUserGrpcRequest) returns (DeleteUserGrpcResponse);
}

message RegisterUserGrpcRequest {
	string login = 1;
	string email = 2;
	string password = 3;
}

message RegisterUserGrpcResponse {
	string userId = 1;
	string error = 2;
}

message UpdateUserGrpcRequest {
	string userId = 1;
	string login = 2;
	string email = 3;
	string password = 4;
	string friends = 5;
	string groups = 6;
	string chanels = 7;
}

message UpdateUserGrpcResponse {
	string error = 1;
}

message AuthenticationUserGrpcRequest {
	string login = 1;
	string password = 2;
}

message AuthenticationUserGrpcResponse {
	string userId = 1;
	string error = 2;
}

message GetUserGrpcRequest {
	string login = 1;
}

message GetUserGrpcResponse {
	string login = 1;
	string registerationDate = 2;
	string friends = 3;
	string groups = 4;
	string chanels = 5;
	string error = 6;
}

message DeleteUserGrpcRequest {
	string userId = 1;
	string password = 2;
}

message DeleteUserGrpcResponse {
	string error = 1;
}
